### ISSUE TITLE
Add `isErr` and `isOk` functional helper functions for `Array.filter` type narrowing

### ISSUE THREAD

**Issue by patroza** [gDelgado14/neverthrow#4]
It seems calling `.filter(x => x.isErr())` or `.isOk()` does not narrow the type in the output type
However with functional helper functions it does: `.filter(isErr)` or `isOk`:

```
export const isErr = <T, TErr>(x: Result<T, TErr>): x is Err<T, TErr> => x.isErr()
export const isOk = <T, TErr>(x: Result<T, TErr>): x is Ok<T, TErr> => x.isOk()
```

**Comment by gDelgado14** [comment]
The foreseen gain from this does not seem worth it given that this would increase the surface area of what is intended to be a very simple module. I'd recommend just making this a utility function within your codebase.

**Comment by Johann01** [comment]
Thank you for opening up this issue! Literally saved me hours and a lot of typecasting!

**Comment by Johann01** [comment]
A small update of that utility, becaus eit helped me a lot:
export const isOk = <T, E>(result: Ok<T, never> | Err<never, E>): result is Ok<T, never> => result.isOk()
export const isErr = <T, E>(result: Ok<T, never> | Err<never, E>): result is Err<never, E> => result.isErr()

Since the either the T or E Generic is never, the filtering typescipts type guard check is failing. With adding the never it works.
